// Code generated by MockGen. DO NOT EDIT.
// Source: internal/mcp/agent.go
//
// Generated by this command:
//
//	mockgen -source=internal/mcp/agent.go -destination=tests/mocks/mcp/agent.go -package=mcpmocks -typed
//

// Package mcpmocks is a generated GoMock package.
package mcpmocks

import (
	context "context"
	reflect "reflect"

	guardrails "github.com/inference-gateway/inference-gateway/internal/guardrails"
	otel "github.com/inference-gateway/inference-gateway/otel"
	core "github.com/inference-gateway/inference-gateway/providers/core"
	types "github.com/inference-gateway/inference-gateway/providers/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// ExecuteTools mocks base method.
func (m *MockAgent) ExecuteTools(ctx context.Context, toolCalls []types.ChatCompletionMessageToolCall) ([]types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTools", ctx, toolCalls)
	ret0, _ := ret[0].([]types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteTools indicates an expected call of ExecuteTools.
func (mr *MockAgentMockRecorder) ExecuteTools(ctx, toolCalls any) *MockAgentExecuteToolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTools", reflect.TypeOf((*MockAgent)(nil).ExecuteTools), ctx, toolCalls)
	return &MockAgentExecuteToolsCall{Call: call}
}

// MockAgentExecuteToolsCall wrap *gomock.Call
type MockAgentExecuteToolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentExecuteToolsCall) Return(arg0 []types.Message, arg1 error) *MockAgentExecuteToolsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentExecuteToolsCall) Do(f func(context.Context, []types.ChatCompletionMessageToolCall) ([]types.Message, error)) *MockAgentExecuteToolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentExecuteToolsCall) DoAndReturn(f func(context.Context, []types.ChatCompletionMessageToolCall) ([]types.Message, error)) *MockAgentExecuteToolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockAgent) Run(ctx context.Context, provider core.IProvider, model string, request *types.CreateChatCompletionRequest, response *types.CreateChatCompletionResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, provider, model, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAgentMockRecorder) Run(ctx, provider, model, request, response any) *MockAgentRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAgent)(nil).Run), ctx, provider, model, request, response)
	return &MockAgentRunCall{Call: call}
}

// MockAgentRunCall wrap *gomock.Call
type MockAgentRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentRunCall) Return(arg0 error) *MockAgentRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentRunCall) Do(f func(context.Context, core.IProvider, string, *types.CreateChatCompletionRequest, *types.CreateChatCompletionResponse) error) *MockAgentRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentRunCall) DoAndReturn(f func(context.Context, core.IProvider, string, *types.CreateChatCompletionRequest, *types.CreateChatCompletionResponse) error) *MockAgentRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunWithStream mocks base method.
func (m *MockAgent) RunWithStream(ctx context.Context, provider core.IProvider, model string, middlewareStreamCh chan []byte, body *types.CreateChatCompletionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithStream", ctx, provider, model, middlewareStreamCh, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithStream indicates an expected call of RunWithStream.
func (mr *MockAgentMockRecorder) RunWithStream(ctx, provider, model, middlewareStreamCh, body any) *MockAgentRunWithStreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithStream", reflect.TypeOf((*MockAgent)(nil).RunWithStream), ctx, provider, model, middlewareStreamCh, body)
	return &MockAgentRunWithStreamCall{Call: call}
}

// MockAgentRunWithStreamCall wrap *gomock.Call
type MockAgentRunWithStreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentRunWithStreamCall) Return(arg0 error) *MockAgentRunWithStreamCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentRunWithStreamCall) Do(f func(context.Context, core.IProvider, string, chan []byte, *types.CreateChatCompletionRequest) error) *MockAgentRunWithStreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentRunWithStreamCall) DoAndReturn(f func(context.Context, core.IProvider, string, chan []byte, *types.CreateChatCompletionRequest) error) *MockAgentRunWithStreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetGuardrails mocks base method.
func (m *MockAgent) SetGuardrails(evaluator *guardrails.Evaluator, telemetry otel.OpenTelemetry, failMode string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGuardrails", evaluator, telemetry, failMode)
}

// SetGuardrails indicates an expected call of SetGuardrails.
func (mr *MockAgentMockRecorder) SetGuardrails(evaluator, telemetry, failMode any) *MockAgentSetGuardrailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGuardrails", reflect.TypeOf((*MockAgent)(nil).SetGuardrails), evaluator, telemetry, failMode)
	return &MockAgentSetGuardrailsCall{Call: call}
}

// MockAgentSetGuardrailsCall wrap *gomock.Call
type MockAgentSetGuardrailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentSetGuardrailsCall) Return() *MockAgentSetGuardrailsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentSetGuardrailsCall) Do(f func(*guardrails.Evaluator, otel.OpenTelemetry, string)) *MockAgentSetGuardrailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentSetGuardrailsCall) DoAndReturn(f func(*guardrails.Evaluator, otel.OpenTelemetry, string)) *MockAgentSetGuardrailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
